"""add_user_registration_fields

Revision ID: ebf112457011
Revises: e69999560f4f
Create Date: 2025-09-19 17:59:19.245765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebf112457011'
down_revision: Union[str, None] = 'e69999560f4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('university', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('career_goal', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('contract_types', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('email_verified_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'location')
    op.drop_column('users', 'contract_types')
    op.drop_column('users', 'career_goal')
    op.drop_column('users', 'university')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
